### ISSUE TITLE
Support gcp auth provider

### ISSUE THREAD

**Issue by RutledgePaulV** [RutledgePaulV/kube-api#6]
Apparently GCP uses a custom provider in this format.. not sure why they use a custom thing instead of using the exec auth but would be nice to support it out of the box.

```yaml
users:
- name: gke_cluster_name
  user:
    auth-provider:
      config:
        access-token: <access_token>
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: <timestamp>
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
